name: sfac_design_flutter
description: 스나이퍼팩토리 디자인시스템 플러터 패키지
version: 1.0.0+1
homepage: 'https://github.com/sniperfactory-official/sfac-designkit-flutter'



environment:
  sdk: '>=3.0.3 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
  flutter_svg: ^2.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.example.sfac_design_flutter
        pluginClass: SfacDesignFlutterPlugin
      ios:
        pluginClass: SfacDesignFlutterPlugin

  assets:
    - images/